### ISSUE TITLE
Where is Jupyter Notebook?

### ISSUE THREAD

**Issue by bernardelli** [cgorman/tensorflow-som#2]
On `SelfOrganizingMap.__init__`, there is a parameter called `output_sensitivity` whose description is "The constant controlling the width of the activity gaussian. See the Jupyter Notebook for an explanation.", but the repository has no notebook.

**Comment by cgorman** [comment]
Oops haha good catch. Yeah I think I was originally going to put it in a notebook as a tutorial but I found myself just completely repeating the comments so I tossed it. I'll remove the comment and upload the figure I mention when I get a chance, thanks!

**Comment by bernardelli** [comment]
Thanks!

**Comment by cgorman** [comment]
I added the explanation to the readme, sorry for the delay!
