### ISSUE TITLE
Fix _make_activity_op

### ISSUE THREAD

**Issue by bernardelli** [cgorman/tensorflow-som#3]
I am completely new to tensor flow, but I think I might have found a bug.

I was trying to get the network output with `_make_activity_op`, but the function would only return a empty tensor. After changing:

```
dist = tf.norm(tf.subtract(
tf.expand_dims(self._weights, axis=0),
tf.expand_dims(input_tensor, axis=1)),
name="Distance")
```

to 

```
dist = tf.norm(tf.subtract(
tf.expand_dims(self._weights, axis=0),
tf.expand_dims(input_tensor, axis=1)),
name="Distance", axis = 2)
```

the output would be just fine.

**Comment by cgorman** [comment]
Hey thanks, I don't know why it took me a month to fix this but it should be ok now :)
