### ISSUE TITLE
Mini-batch training incorrectly implemented?

### ISSUE THREAD

**Issue by felix-hilden** [cgorman/tensorflow-som#5]
If I've read the source code right, `batch_size` is only used in the train function. And there it doesn't affect the training loop in any way but the number of loops being `epochs * batch_size`. So now each epoch of training is just repeated a bunch of times.

Is it intentional? I think one should divide the data into `batch_size`-sized chunks and perform one training step with that data, then move on until all data is used. Then the next epoch. It's even noted in the docstring: 

> :param batch_size: Number of input vectors to train on at a time

Maybe I missed something, but in case I didn't, here's an issue. Or maybe batch training without the "mini" is intended to just repeat the training. Anyways.

Cheers!

**Comment by cgorman** [comment]
Hi Felix, I can see why this is confusing, the SOM code itself makes few assumptions about the structure of the data it receives. Instead, the batching is handled by the caller. For example, [these lines](https://github.com/cgorman/tensorflow-som/blob/master/example.py#L68-L73) in the example script use the tensorflow datasets interface to handle the batching. The SOM code just gets the iterator and pulls however many tensors that the iterator specifies. The loop in the training function needs to know the batch size to make sure it doesn't loop too many times and exhaust the data stream.

Hope that makes sense, let me know if you have any further questions!

**Comment by felix-hilden** [comment]
I see, thanks for the clarification!
