### ISSUE TITLE
Fix get_centroids and map_vects functions

### ISSUE THREAD

**Issue by nitishkannan23** [cgorman/tensorflow-som#8]
Hey,

I have been using your code to learn SOM and run few iterations on my data. But I find the functions get_centroids and map_vects seem to be out of place. Can you please fix these functions according to you tf_som.py code. It will be helpful in my SOM learning process.

Thanks!

**Comment by cgorman** [comment]
Hi, sorry but I'm not adding new features to this project, but if you would like to open a pull request with these functions I'd be glad to merge them. Thanks!

**Comment by nitishkannan23** [comment]
Hi,

I have sent a pull request to calculate BMU Indices for input vectors.

Thanks,
Nitish
